### ISSUE TITLE
what happen to the list of nodes in contrib/seeds?

### ISSUE THREAD

**Issue by cryptforall** [qbic-platform/qbic#4]
Well you can't have people connect wallets and stare at src/chainparamsseeds.h with no nodes listed in /contrib/seeds/nodes_main.txt. Need an admin that has the  ip of nodes to add it in the file.

**Comment by cryptforall** [comment]
[peers.txt](https://github.com/qbic-platform/qbic/files/1892895/peers.txt)
quick Fix just rename to peers.dat
and paste in your roaming folder. C:\Users\<user name>\AppData\Roaming\QbicCore

**Comment by onemichaelrossi** [comment]
I’ll take this to the groups.....

**Comment by cryptforall** [comment]
fixed the node list, we can add more in future
